# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# CLOUDINARY_URL: 'cloudinary://237783839854683:KY6S8b-saTEYlIYX4ZnncH82U-w@dxjrnyrcp' #Cle Baptiste
CLOUDINARY_URL: "cloudinary://774944727884551:lk-mzybg1LZ47QUbOOWOjzHzNKk@dpthh89hv"

# Keys Xavier
GOOGLE_API_SERVER_KEY: AIzaSyCMpAD2UonEhKF4p5jiwWFh2vqdzZCyQPM
GOOGLE_API_BROWSER_KEY: AIzaSyCE0BGoeMJRcRutXjuognITO6pDkgAoEQI



development:
  FB_ID: "604094813268202"
  FB_SECRET: "909c619305315dae4c993efcd7964af4"

production:
  FB_ID: "426614874446638"
  FB_SECRET: "6610983097929b55f579e74ea2dcecd1"
  FOREST_ENV_SECRET: "405ab718506f9b98667c319e5a07fb970cfb181d7e5f2990a0f4c97865b21801"
  FOREST_AUTH_SECRET: "4ma7kJI55b17CDiMLOiA7pzxxPqK8asM"
